### ISSUE TITLE
Change the name to "Auto Actions"

### ISSUE THREAD

**Issue by phate09** [phate09/ToDoChores#13]
Ideas?
Other names?
Everybody agrees?

**Comment by taichunmin** [comment]
There are already a mod named "Auto Actions"
<http://steamcommunity.com/sharedfiles/filedetails/?id=651419070>

**Comment by 1to3fall5** [comment]
auto survive
easy survive
one click 
one click action 
one click survive
auto gathering
auto find
I tried haha, can't think of any other names

**Comment by taichunmin** [comment]
1. Actions Bot
2. Chores Bot
3. Bot
