### ISSUE TITLE
Just updated v2.0.1, game crashed.

### ISSUE THREAD

**Issue by SCTaco** [phate09/ToDoChores#19]
Just updated and tried to fertilize my berry bushes, game crashed immediately.

Here's what it says upon crashing: https://gyazo.com/83fec08b446c3888b2db53cda09e8851

For the moment, I've been trying to find a way to downgrade to version 1.5, but I haven't figured it out. I would think it's somewhere on Github if not on steam?

**Comment by SCTaco** [comment]
Update: I tried to cut down trees with the mod as well, and that worked fine. The issue seems to happen when you fertilize.

**Comment by phate09** [comment]
Still error after the update?

Best regards,
Edoardo

On 16 Nov 2017, at 00:59, SCTaco <notifications@github.com<mailto:notifications@github.com>> wrote:


Update: I tried to cut down trees with the mod as well, and that worked fine. The issue seems to happen when you fertilize.

**Comment by SCTaco** [comment]
Yeah, this error occurs because I updated. Also, I think that moving the
tree stump removal is now sort of manual, i.e having to click shovel after tree
chopping. If I can get version 1.5 again, that'd be great ;)

**Comment by taichunmin** [comment]
<https://github.com/phate09/ToDoChores/blob/master/scripts/components/ChoresHelpers.lua#L148>
There is a typo, I will fix that as soon as possible. Thanks for report.

**Comment by SCTaco** [comment]
Thank you :)

**Comment by taichunmin** [comment]
@SCTaco I move stump option to shovel because change tool between axe and shovel is vary waste of time. You can find a option with a log icon in shovel task row.

**Comment by taichunmin** [comment]
@SCTaco If you want to downgrade, you can download older version and manually paste to mods folder. Sorry for that.

**Comment by taichunmin** [comment]
link for [version 1.5](https://github.com/phate09/ToDoChores/tree/6b77ce16cb58adc33c3101e1449a734f21c8001b)
download zip file, unzip files, paste to mods folder as below:

- PC: `C:\Program Files\dontstarve\mods`
- Mac: `/Applications/Don't Starve/Don't Starve.app/Contents/mods/`
- Linux: `/home/username/.local/share/Steam/SteamApps/common/dont_starve/mods`

tutorial: <http://support.kleientertainment.com/customer/portal/articles/1360841-how-do-i-download-and-activate-mods-for-don-t-starve->

**Comment by SCTaco** [comment]
Thanks for the help guys, keep up the good work. Amazing mod :)

**Comment by phate09** [comment]
I rolled back so there are no issues for other users

Best regards,
Edoardo

On 16 Nov 2017, at 02:35, SCTaco <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for the help guys, keep up the good work. Amazing mod :)

**Comment by taichunmin** [comment]
@SCTaco 
I have already fix this error and push to unstable mod.
Please give it a try. Thanks.
http://steamcommunity.com/sharedfiles/filedetails/?id=950413860

**Comment by taichunmin** [comment]
currently is in v2.0.2
