### ISSUE TITLE
cave support (by Vezérszattyán)

### ISSUE THREAD

**Issue by taichunmin** [phate09/ToDoChores#6]
```
Vezérszattyán: maybe auto harvest reed or light bulbs in the future? 
```

**Comment by phate09** [comment]
shouldn't be too difficult, i think it is a good idea

**Comment by taichunmin** [comment]
I only worry that the widget buttons will be too much.

**Comment by phate09** [comment]
true, shall we make a second row? for picking? or better to differentiate between "pick" (like bushes) and "pickup" (like flint)

**Comment by taichunmin** [comment]
Another choice is auto switch between cave and normal world,
Because it will reload all mods

**Comment by phate09** [comment]
True, i like the idea for the lightbulbs
But reed is also present in normal world: should we just simply add another one for reeds for now and later substitute the icons (including lightbulbs in the list) when somebody goes to the caves?

**Comment by taichunmin** [comment]
done. close.
